### PR TITLE
Upgrade Handlebars, Bootstrap

### PR DESCRIPTION
**Pull request by ryanmark**
## What is this?

This updates handlebars from 3.0.3 -> 4.0.5, and updates bootstrap from 3.2.0 -> 3.3.2.

## Why?

Versions of handlebars < 4.0.5 have an XSS vulnerabillity:
https://github.com/wycats/handlebars.js/commit/83b8e846a3569bd366cf0b6bdc1e4604d1a2077e

And I was not able to build alpaca with 3.2.0 because it's no longer available to install via Bower. Updated to 3.3.2.

### CODE REVIEW

**Comment by uzquiano** [comment]
That's awesome.  Thanks for this!  I will look closer tonight and do the merge.  Cheers.

**Comment by peterskogsberg** [comment]
Awaiting this one eagerly! :) best regards

**Comment by ryanmark** [comment]
Fixed a few bugs related to handlebars upgrade ^

**Comment by uzquiano** [comment]
Apart from the one change you made to container-array-toolbar for the ../.. relative path, are there any other templates that were affected?  Did Handlebars 4 change the nesting assumptions?

Looks like latest Bootstrap is no problem.  Will Handlebars 4 require more changes to other templates or was that all?

**Comment by ryanmark** [comment]
We've been running this in prod for a couple months now, and haven't had further problems. We did not QA all templates tho.

**Comment by ryanmark** [comment]
This PR is no longer pointing to the correct thing

**Pull request closed without merging**
